# Generated by Django 5.2.5 on 2025-08-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Backend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("device_type", models.CharField(max_length=32)),
                ("qubit_count", models.IntegerField()),
                ("operational", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=128, unique=True)),
                ("submitted_at", models.DateTimeField()),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(max_length=32)),
                (
                    "backend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.backend"
                    ),
                ),
            ],
        ),
    ]
