# Generated by Django 5.2.5 on 2025-08-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("throughput", models.FloatField()),
                ("failure_rate", models.FloatField()),
                ("avg_execution_time", models.FloatField()),
                ("qubit_efficiency", models.FloatField()),
                (
                    "backend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.backend"
                    ),
                ),
            ],
        ),
    ]
