# Generated by Django 5.2.5 on 2025-08-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_metric"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="execution_time",
        ),
        migrations.AddField(
            model_name="job",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="user_id",
            field=models.CharField(default="User", max_length=128),
        ),
        migrations.DeleteModel(
            name="Metric",
        ),
    ]
